name: "Check SDK Size"
on:
  pull_request:
    branches:
      - production

jobs:
  size-check:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Size limit check
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size
          clean_script: clean
